### ISSUE TITLE
Width and height of embedded patch is too small

### ISSUE THREAD

**Issue by androvisuals** [cables-gl/cables-wordpress-plugin#4]
Right now using the short embed code like this 
![image](https://user-images.githubusercontent.com/19530188/70637515-a5489d80-1c37-11ea-8198-5b325651b093.png)

means the image is this size 

![image](https://user-images.githubusercontent.com/19530188/70637561-b5f91380-1c37-11ea-820d-186c04ccf6c9.png)

It'd be great if a user can define the width and the height of a patch like this:

[cables_patch id='5def72a9a727ce2d5684188b' canvas_settings='width 720' 'height 480' 'scale canvas 0.75']

So here we can define the width, height and the scale, maybe it's a great way to enable users to define how it should be.
Some other options could be center, allow fullscreen etc tec..

**Comment by steam0r** [comment]
release 0.11.0 now allows for some more customization of patch width/height and styles and has a sane 0.75 scaled default with a 100% width. all the other stuff should be done in CSS, i think.

update should be possible through the wordpress update function (check for updates/update)
